// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:make_a_habbit/data/models/concluded_habits/concluded_habits_model.dart';
import 'package:make_a_habbit/data/models/habits/habit_frequency.dart';
import 'package:make_a_habbit/data/models/habits/habit_frequency_type.dart';
import 'package:make_a_habbit/data/models/habits/habit_model.dart';
import 'package:make_a_habbit/data/models/habits/habit_type.dart';
import 'package:make_a_habbit/data/models/notifications/notification_config_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ConcludedHabitsModelAdapter());
    registerAdapter(HabitConclusionTypeAdapter());
    registerAdapter(HabitFrequencyAdapter());
    registerAdapter(HabitFrequencyTypeAdapter());
    registerAdapter(HabitModelAdapter());
    registerAdapter(NotificationConfigModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ConcludedHabitsModelAdapter());
    registerAdapter(HabitConclusionTypeAdapter());
    registerAdapter(HabitFrequencyAdapter());
    registerAdapter(HabitFrequencyTypeAdapter());
    registerAdapter(HabitModelAdapter());
    registerAdapter(NotificationConfigModelAdapter());
  }
}
